pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/angular7

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: src/angular7

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'src/angular7/dist'

- task: Npm@1
  displayName: 'Test Angular'
  inputs:
    command: custom
    customCommand: run test -- --watch=false --code-coverage
    workingDir: src/angular7

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage Angular results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'src/angular7/coverage/cobertura-coverage.xml'
    reportDirectory: src/angular7/coverage
    failIfCoverageEmpty: true
